server:
  port: 8081

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/shopsphere_products
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: oFwcn6TbbxvmRvTBEl7vif/On/PRFhUJs5HxQHjt0iw=